# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
site_domain: patagonia-test.netlify.app
collections:
  - name: 'parks'
    label: 'Park'
    folder: '_parks/'
    create: true
    fields:
      - { label: "Park Name", name: "title", widget: "string" }