# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'

collections:
  - name: 'parks'
    label: 'Park'
    folder: '_parks/'
    create: true
    slug: {{slug}}
    fields:
      - { label: "Park Name", name: 'name', widget: "string" }